[package]
name = "heartflow-commands"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
description = "Slash command handlers for heartflow"
publish.workspace = true

[lib]
name = "commands"

[lints]
workspace = true

[dependencies]
runtime = { workspace = true }
